PROJECT = example1
DEPS = esphi
NO_AUTOPATCH = esphi
dep_esphi = git https://github.com/brigadier/esphi master
#export ERL_TOP=~/.kerl/builds/18.2/otp_src_18.2/
#SHELL_ERL=$(ERL_TOP)/bin/cerl -debug
include erlang.mk
